FROM openjdk:11.0.9-slim
WORKDIR '/webapp'
ARG ARTIFACT_NAME=demo-0.0.1-SNAPSHOT.jar
ARG ARTIFACT_PATH=target/${ARTIFACT_NAME}
COPY ${ARTIFACT_PATH} .
ENV SERVER_PORT=8081
EXPOSE 8081
ENTRYPOINT ["java", "-jar", "demo-0.0.1-SNAPSHOT.jar"]